const Promise = require('bluebird');
const db = require('./db');

const { Crop } = require('./models');

// What is an indicator for sowing outdoors before last frost and sowing outdoors before first frost?

const crops = [
    {
        commonName: 'Arugula',
        latinName: 'Eruca sativa',
        family: 'Cabbage',
        seedDepth: 0.25,
        minGermTemp: 40,
        maxGermTemp: 55,
        minGermTime: 5,
        maxGermTime: 7,
        sowOutdoorsBeforeLastFrost: 4,
        sowOutdoorsBeforeFirstFrost: 8,
        minSoilPh: 6.0,
        maxSoilPh: 7.0,
        minGrowTemp: 50,
        maxGrowTemp: 65,
        seedSpacing: 1,
        thinTo: 6,
        rowSpacing: 6,
        waterFreq: 'med',
        nitrogenReq: 'low',
        phosphorusReq: 'low',
        potassiumReq: 'low',
        sunExposure: 'full',
        minDaysToMaturity: 20,
        maxDaysToMaturity: 30,
    },
    {
        commonName: 'Beans (bush)',
        latinName: 'Phaseolus vulgaris',
        family: 'Pea',
        seedDepth: 1.0,
        minGermTemp: 75,
        maxGermTemp: 85,
        minGermTime: 7,
        maxGermTime: 10,
        sowOutdoorsBeforeLastFrost: 0,
        sowOutdoorsBeforeFirstFrost: 11,
        minSoilPh: 6.5,
        maxSoilPh: 7.5,
        minGrowTemp: 60,
        maxGrowTemp: 65,
        seedSpacing: 4,
        rowSpacing: 8,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'low',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        minFlowerToHarvestTime: 10,
        maxFlowerToHarvestTime: 14,
        minDaysToMaturity: 50,
        maxDaysToMaturity: 70,
    },
    {
        commonName: 'Beans (fava)',
        latinName: 'Vicia faba',
        family: 'Pea',
        seedDepth: 1.0,
        minGermTemp: 55,
        maxGermTemp: 75,
        minGermTime: 7,
        maxGermTime: 10,
        sowOutdoorsBeforeLastFrost: 0,
        sowOutdoorsBeforeFirstFrost: 11,
        minSoilPh: 6.5,
        maxSoilPh: 7.5,
        minGrowTemp: 60,
        maxGrowTemp: 65,
        seedSpacing: 4,
        rowSpacing: 8,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'low',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        minFlowerToHarvestTime: 10,
        maxFlowerToHarvestTime: 14,
        baseGdd: 50,
        minDaysToMaturity: 50,
        maxDaysToMaturity: 70,
    },
    {
        commonName: 'Beans (pole)',
        latinName: 'Phaseolus vulgaris',
        family: 'Pea',
        seedDepth: 1,
        minGermTemp: 65,
        maxGermTemp: 85,
        minGermTime: 7,
        maxGermTime: 10,
        sowOutdoorsBeforeLastFrost: 0,
        sowOutdoorsBeforeFirstFrost: 11,
        minSoilPh: 6.5,
        maxSoilPh: 7.5,
        minGrowTemp: 60,
        maxGrowTemp: 65,
        seedSpacing: 3,
        waterFreq: 'med',
        sunExposure: 'full',
        nitrogenReq: 'low',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        minFlowerToHarvestTime: 10,
        maxFlowerToHarvestTime: 14,
        baseGdd: 50,
        minDaysToMaturity: 45,
        maxDaysToMaturity: 60,
    },
    {
        commonName: 'Beets',
        latinName: 'Beta vulgaris',
        family: 'Beet',
        seedDepth: 0.5,
        minGermTemp: 75,
        maxGermTemp: 85,
        minGermTime: 5,
        sowIndoorsBeforeLastFrost: 5,
        transplantBeforeLastFrost: 2,
        sowOutdoorsBeforeLastFrost: 4,
        sowOutdoorsBeforeFirstFrost: 10,
        minSoilPh: 6.0,
        maxSoilPh: 7.5,
        minGrowTemp: 65,
        maxGrowTemp: 75,
        seedSpacing: 3,
        waterFreq: 'med',
        sunExposure: 'full',
        nitrogenReq: 'low',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        gddToMaturity: 1253,
        baseGdd: 40,
        minDaysToMaturity: 50,
        maxDaysToMaturity: 70,
    },
    {
        commonName: 'Broccoli',
        latinName: 'Brassica olerecea',
        family: 'Cabbage',
        seedDepth: 0.25,
        minGermTemp: 68,
        maxGermTemp: 85,
        minGermTime: 4,
        maxGermTime: 7,
        sowIndoorsBeforeLastFrost: 8,
        transplantBeforeLastFrost: 2,
        sowOutdoorsBeforeFirstFrost: 16,
        minSoilPh: 6.5,
        maxSoilPh: 7.5,
        minGrowTemp: 60,
        maxGrowTemp: 65,
        seedSpacing: 16,
        rowSpacing: 12,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'med',
        phosphorusReq: 'high',
        potassiumReq: 'high',
        gddToMaturity: 571,
        baseGdd: 40,
        minDaysToMaturity: 50,
        maxDaysToMaturity: 65,
    },
    {
        commonName: 'Brussels Sprouts',
        latinName: 'Brassica olerecea',
        family: 'Cabbage',
        seedDepth: 0.25,
        minGermTemp: 75,
        maxGermTemp: 85,
        minGermTime: 5,
        maxGermTime: 8,
        sowIndoorsBeforeLastFrost: 6,
        transplantBeforeLastFrost: 2,
        sowOutdoorsBeforeFirstFrost: 16,
        minSoilPh: 6.0,
        maxSoilPh: 6.8,
        minGrowTemp: 60,
        maxGrowTemp: 65,
        seedSpacing: 16,
        rowSpacing: 12,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'med',
        phosphorusReq: 'high',
        potassiumReq: 'high',
        baseGdd: 40,
        minDaysToMaturity: 80,
        maxDaysToMaturity: 100,
    },
    {
        commonName: 'Cabbage',
        latinName: 'Brassica olerecea',
        family: 'Cabbage',
        seedDepth: 0.25,
        minGermTemp: 75,
        maxGermTemp: 85,
        minGermTime: 5,
        maxGermTime: 5,
        sowIndoorsBeforeLastFrost: 6,
        transplantBeforeLastFrost: 2,
        sowOutdoorsBeforeFirstFrost: 12,
        minSoilPh: 6.0,
        maxSoilPh: 7.5,
        minGrowTemp: 60,
        maxGrowTemp: 65,
        seedSpacing: 12,
        rowSpacing: 12,
        sunExposure: 'full',
        waterFreq: 'high',
        nitrogenReq: 'high',
        phosphorusReq: 'high',
        potassiumReq: 'high',
        baseGdd: 40,
        minDaysToMaturity: 60,
        maxDaysToMaturity: 90,
    },
    {
        commonName: 'Carrot',
        latinName: 'Daucus carota',
        family: 'Carrot',
        seedDepth: 0.25,
        minGermTemp: 75,
        minGermTime: 6,
        maxGermTime: 6,
        sowOutdoorsBeforeLastFrost: 2,
        sowOutdoorsBeforeFirstFrost: 12,
        minSoilPh: 5.5,
        maxSoilPh: 6.5,
        minGrowTemp: 60,
        maxGrowTemp: 70,
        seedSpacing: 2,
        rowSpacing: 9,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'med',
        phosphorusReq: 'low',
        potassiumReq: 'low',
        gddToMaturity: 550,
        baseGdd: 38,
        minDaysToMaturity: 60,
        maxDaysToMaturity: 80,
    },
    {
        commonName: 'Cauliflower',
        latinName: 'Brassica olerecea',
        family: 'Cabbage',
        seedDepth: 0.25,
        minGermTemp: 80,
        minGermTime: 6,
        maxGermTime: 6,
        sowIndoorsBeforeLastFrost: 6,
        transplantBeforeLastFrost: 2,
        sowOutdoorsBeforeLastFrost: 0,
        sowOutdoorsBeforeFirstFrost: 12,
        minSoilPh: 6.5,
        maxSoilPh: 7.5,
        minGrowTemp: 60,
        maxGrowTemp: 70,
        seedSpacing: 15,
        rowSpacing: 12,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'high',
        phosphorusReq: 'high',
        potassiumReq: 'high',
        baseGdd: 40,
        minDaysToMaturity: 55,
        maxDaysToMaturity: 80,
    },
    {
        commonName: 'Celery',
        latinName: 'Apium graveolens',
        family: 'Carrot',
        seedDepth: 0,
        minGermTemp: 70,
        minGermTime: 7,
        sowIndoorsBeforeLastFrost: 10,
        transplantBeforeLastFrost: -1,
        sowOutdoorsBeforeFirstFrost: 20,
        minSoilPh: 6.0,
        maxSoilPh: 7.0,
        minGrowTemp: 60,
        maxGrowTemp: 70,
        seedSpacing: 8,
        rowSpacing: 12,
        sunExposure: 'full',
        waterFreq: 'high',
        nitrogenReq: 'high',
        phosphorusReq: 'high',
        potassiumReq: 'high',
        minDaysToMaturity: 80,
        maxDaysToMaturity: 100,
    },
    {
        commonName: 'Corn',
        latinName: 'Zea mays',
        family: 'Grass',
        seedDepth: 1.0,
        minGermTemp: 80,
        minGermTime: 4,
        sowOutdoorsBeforeLastFrost: -1,
        sowOutdoorsBeforeFirstFrost: 14,
        minSoilPh: 6.0,
        maxSoilPh: 7.0,
        minGrowTemp: 65,
        maxGrowTemp: 75,
        seedSpacing: 8,
        sunExposure: 'full',
        waterFreq: 'high',
        nitrogenReq: 'high',
        phosphorusReq: 'high',
        potassiumReq: 'high',
        minFlowerToHarvestTime: 18,
        maxFlowerToHarvestTime: 21,
        gddToMaturity: 1667,
        baseGdd: 50,
        minDaysToMaturity: 70,
        maxDaysToMaturity: 105,
    },
    {
        commonName: 'Cucumber',
        latinName: 'Cucumis sativus',
        family: 'Cucumber',
        seedDepth: 0.5,
        minGermTemp: 80,
        maxGermTemp: 95,
        minGermTime: 3,
        maxGermTime: 4,
        sowIndoorsBeforeLastFrost: 3,
        transplantBeforeLastFrost: -2,
        sowOutdoorsBeforeLastFrost: 0,
        sowOutdoorsBeforeFirstFrost: 12,
        minSoilPh: 6.0,
        maxSoilPh: 7.0,
        minGrowTemp: 70,
        maxGrowTemp: 80,
        seedSpacing: 18,
        sunExposure: 'full',
        waterFreq: 'high',
        nitrogenReq: 'med',
        phosphorusReq: 'high',
        potassiumReq: 'high',
        minFlowerToHarvestTime: 8,
        maxFlowerToHarvestTime: 10,
        gddToMaturity: 1207,
        baseGdd: 55,
        minDaysToMaturity: 55,
        maxDaysToMaturity: 65,
    },
    {
        commonName: 'Eggplant',
        latinName: 'Solanum melongena',
        family: 'Tomato',
        seedDepth: 0.25,
        minGermTemp: 85,
        minGermTime: 7,
        sowIndoorsBeforeLastFrost: 6,
        transplantBeforeLastFrost: -2,
        sowOutdoorsBeforeFirstFrost: 18,
        minSoilPh: 5.5,
        maxSoilPh: 7.0,
        minGrowTemp: 80,
        maxGrowTemp: 90,
        seedSpacing: 18,
        sunExposure: 'full',
        waterFreq: 'high',
        nitrogenReq: 'med',
        phosphorusReq: 'high',
        potassiumReq: 'high',
        minFlowerToHarvestTime: 40,
        maxFlowerToHarvestTime: 50,
        baseGdd: 60,
        minDaysToMaturity: 75,
        maxDaysToMaturity: 90,
    },
    {
        commonName: 'Garlic',
        latinName: 'Allium sativum',
        family: 'Onion',
        seedDepth: 2,
        minGermTemp: 55,
        minGermTime: 0,
        sowOutdoorsBeforeFirstFrost: 10,
        minSoilPh: 6.0,
        maxSoilPh: 7.0,
        minGrowTemp: 55,
        maxGrowTemp: 75,
        seedSpacing: 6,
        sunExposure: 'full',
        waterFreq: 'low',
        nitrogenReq: 'med',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        minDaysToMaturity: 90,
    },
    {
        commonName: 'Kale',
        latinName: 'Brassica olerecea',
        family: 'Cabbage',
        seedDepth: 0.25,
        minGermTemp: 45,
        maxGermTemp: 95,
        minGermTime: 5,
        maxGermTime: 7,
        sowIndoorsBeforeLastFrost: 6,
        transplantBeforeLastFrost: 2,
        sowOutdoorsBeforeLastFrost: 0,
        sowOutdoorsBeforeFirstFrost: 14,
        minSoilPh: 6.0,
        maxSoilPh: 7.0,
        minGrowTemp: 60,
        maxGrowTemp: 65,
        seedSpacing: 16,
        sunExposure: 'full',
        waterFreq: 'high',
        nitrogenReq: 'med',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        baseGdd: 40,
        minDaysToMaturity: 50,
        maxDaysToMaturity: 70,
    },
    {
        commonName: 'Leeks',
        latinName: 'Allium ampeloprasum',
        family: 'Onion',
        seedDepth: 0.25,
        minGermTemp: 75,
        minGermTime: 5,
        maxGermTime: 7,
        sowIndoorsBeforeLastFrost: 8,
        transplantBeforeLastFrost: 2,
        minSoilPh: 6.0,
        maxSoilPh: 7.5,
        minGrowTemp: 60,
        seedSpacing: 6,
        rowSpacing: 12,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'med',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        baseGdd: 40,
        minDaysToMaturity: 100,
        maxDaysToMaturity: 120,
    },
    {
        commonName: 'Lettuce (leaf)',
        latinName: 'Lactuca sativa',
        family: 'Sunflower',
        seedDepth: 0.25,
        minGermTemp: 40,
        maxGermTemp: 60,
        minGermTime: 7,
        maxGermTime: 14,
        sowIndoorsBeforeLastFrost: 6,
        transplantBeforeLastFrost: 2,
        sowOutdoorsBeforeLastFrost: 0,
        sowOutdoorsBeforeFirstFrost: 11,
        minSoilPh: 6.5,
        maxSoilPh: 7.0,
        minGrowTemp: 55,
        maxGrowTemp: 65,
        seedSpacing: 1,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'high',
        phosphorusReq: 'high',
        potassiumReq: 'high',
        baseGdd: 40,
        gddToMaturity: 1367,
        minDaysToMaturity: 45,
        maxDaysToMaturity: 60,
    },
    {
        commonName: 'Lettuce (head)',
        latinName: 'Lactuca sativa',
        family: 'Sunflower',
        seedDepth: 0.25,
        minGermTemp: 40,
        maxGermTemp: 60,
        minGermTime: 7,
        maxGermTime: 14,
        sowIndoorsBeforeLastFrost: 6,
        transplantBeforeLastFrost: 2,
        sowOutdoorsBeforeLastFrost: 0,
        sowOutdoorsBeforeFirstFrost: 12,
        minSoilPh: 6.5,
        maxSoilPh: 7.0,
        minGrowTemp: 55,
        maxGrowTemp: 65,
        seedSpacing: 10,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'high',
        phosphorusReq: 'high',
        potassiumReq: 'high',
        baseGdd: 40,
        gddToMaturity: 1367,
        minDaysToMaturity: 60,
        maxDaysToMaturity: 70,
    },
    {
        commonName: 'Melon',
        latinName: 'Cucumis melo',
        family: 'Cucumber',
        seedDepth: 0.5,
        minGermTemp: 80,
        maxGermTemp: 90,
        minGermTime: 3,
        maxGermTime: 5,
        sowIndoorsBeforeLastFrost: 3,
        transplantBeforeLastFrost: -2,
        sowOutdoorsBeforeLastFrost: -2,
        sowOutdoorsBeforeFirstFrost: 16,
        minSoilPh: 6.0,
        maxSoilPh: 7.0,
        minGrowTemp: 70,
        maxGrowTemp: 85,
        seedSpacing: 16,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'low',
        phosphorusReq: 'high',
        potassiumReq: 'high',
        minFlowerToHarvestTime: 40,
        maxFlowerToHarvestTime: 50,
        baseGdd: 50,
        gddToMaturity: 775,
        minDaysToMaturity: 75,
        maxDaysToMaturity: 100,
    },
    {
        commonName: 'Mustard',
        latinName: 'Brassica juncea',
        family: 'Cabbage',
        seedDepth: 0.25,
        minGermTemp: 65,
        maxGermTemp: 70,
        minGermTime: 4,
        maxGermTime: 6,
        sowIndoorsBeforeLastFrost: 4,
        transplantBeforeLastFrost: 2,
        sowOutdoorsBeforeFirstFrost: 10,
        minSoilPh: 5.5,
        maxSoilPh: 7.0,
        minGrowTemp: 50,
        maxGrowTemp: 60,
        seedSpacing: 6,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'high',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        gddToMaturity: 660,
        baseGdd: 40,
        minDaysToMaturity: 30,
        maxDaysToMaturity: 40,
    },
    {
        commonName: 'Okra',
        latinName: 'Abelmoschus esculentus',
        family: 'Mallow',
        seedDepth: 0.75,
        minGermTemp: 80,
        maxGermTemp: 95,
        minGermTime: 5,
        maxGermTime: 14,
        sowIndoorsBeforeLastFrost: 5,
        transplantBeforeLastFrost: -1,
        minSoilPh: 6.0,
        maxSoilPh: 8.0,
        minGrowTemp: 70,
        maxGrowTemp: 90,
        seedSpacing: 12,
        sunExposure: 'full',
        waterFreq: 'low',
        nitrogenReq: 'med',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        baseGdd: 60,
        minDaysToMaturity: 50,
        maxDaysToMaturity: 65,
    },
    {
        commonName: 'Onion',
        latinName: 'Allium cepa',
        family: 'Onion',
        seedDepth: 0.5,
        minGermTemp: 65,
        maxGermTemp: 85,
        minGermTime: 4,
        maxGermTime: 5,
        sowIndoorsBeforeLastFrost: 8,
        transplantBeforeLastFrost: 3,
        minSoilPh: 6.0,
        maxSoilPh: 7.5,
        minGrowTemp: 55,
        maxGrowTemp: 75,
        seedSpacing: 3,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'med',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        baseGdd: 35,
        gddToMaturity: 600,
        minDaysToMaturity: 100,
        maxDaysToMaturity: 120,
    },
    {
        commonName: 'Parsnips',
        latinName: 'Pastinaca sativa',
        family: 'Carrot',
        seedDepth: 0.5,
        minGermTemp: 65,
        maxGermTemp: 75,
        minGermTime: 12,
        maxGermTime: 14,
        sowOutdoorsBeforeLastFrost: 3,
        sowOutdoorsBeforeFirstFrost: 14,
        minSoilPh: 6.0,
        maxSoilPh: 7.0,
        minGrowTemp: 60,
        maxGrowTemp: 65,
        seedSpacing: 4,
        rowSpacing: 4,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'high',
        phosphorusReq: 'low',
        potassiumReq: 'med',
        baseGdd: 40,
        minDaysToMaturity: 110,
        maxDaysToMaturity: 130,
    },
    {
        commonName: 'Peas',
        latinName: 'Pisum sativum',
        family: 'Pea',
        seedDepth: 1,
        minGermTemp: 40,
        maxGermTemp: 75,
        minGermTime: 14,
        sowOutdoorsBeforeLastFrost: 6,
        sowOutdoorsBeforeFirstFrost: 10,
        minSoilPh: 6.0,
        maxSoilPh: 7.0,
        minGrowTemp: 60,
        maxGrowTemp: 65,
        seedSpacing: 1,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'low',
        phosphorusReq: 'low',
        potassiumReq: 'low',
        minFlowerToHarvestTime: 8,
        maxFlowerToHarvestTime: 10,
        gddToMaturity: 2381,
        baseGdd: 40,
        minDaysToMaturity: 55,
        maxDaysToMaturity: 85,
    },
    {
        commonName: 'Peppers',
        latinName: 'Capsicum annuum',
        family: 'Tomato',
        seedDepth: 0.25,
        minGermTemp: 80,
        maxGermTemp: 85,
        minGermTime: 6,
        maxGermTime: 8,
        sowIndoorsBeforeLastFrost: 8,
        transplantBeforeLastFrost: -2,
        sowOutdoorsBeforeFirstFrost: 16,
        minSoilPh: 5.5,
        maxSoilPh: 7.0,
        minGrowTemp: 70,
        maxGrowTemp: 85,
        seedSpacing: 12,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'med',
        phosphorusReq: 'high',
        potassiumReq: 'high',
        minFlowerToHarvestTime: 40,
        maxFlowerToHarvestTime: 50,
        gddToMaturity: 2021,
        baseGdd: 50,
        minDaysToMaturity: 60,
        maxDaysToMaturity: 90,
    },
    {
        commonName: 'Potatoes',
        latinName: 'Solanum tuberosum',
        family: 'Tomato',
        seedDepth: 4,
        minGermTemp: 45,
        minGermTime: 0,
        sowOutdoorsBeforeLastFrost: 3,
        sowOutdoorsBeforeFirstFrost: 13,
        minSoilPh: 5.0,
        maxSoilPh: 6.5,
        minGrowTemp: 60,
        maxGrowTemp: 65,
        seedSpacing: 12,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'high',
        phosphorusReq: 'high',
        potassiumReq: 'high',
        gddToMaturity: 1951,
        baseGdd: 40,
        minDaysToMaturity: 90,
        maxDaysToMaturity: 120,
    },
    {
        commonName: 'Pumpkins',
        latinName: 'Cucurbita pepo',
        family: 'Cucumber',
        seedDepth: 1,
        minGermTemp: 70,
        maxGermTemp: 90,
        minGermTime: 6,
        maxGermTime: 10,
        sowIndoorsBeforeLastFrost: 4,
        sowOutdoorsBeforeLastFrost: -2,
        sowOutdoorsBeforeFirstFrost: 16,
        minSoilPh: 5.5,
        maxSoilPh: 6.5,
        minGrowTemp: 65,
        maxGrowTemp: 75,
        seedSpacing: 18,
        sunExposure: 'full',
        waterFreq: 'high',
        nitrogenReq: 'high',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        minFlowerToHarvestTime: 40,
        maxFlowerToHarvestTime: 60,
        minDaysToMaturity: 85,
        maxDaysToMaturity: 120,
    },
    {
        commonName: 'Radishes',
        latinName: 'Raphanus sativus',
        family: 'Cabbage',
        seedDepth: 0.5,
        minGermTemp: 45,
        maxGermTemp: 90,
        minGermTime: 4,
        maxGermTime: 12,
        sowOutdoorsBeforeLastFrost: 3,
        sowOutdoorsBeforeFirstFrost: 8,
        minSoilPh: 6.0,
        maxSoilPh: 7.0,
        minGrowTemp: 60,
        maxGrowTemp: 65,
        seedSpacing: 1,
        thinTo: 4,
        sunExposure: 'full',
        waterFreq: 'high',
        nitrogenReq: 'low',
        phosphorusReq: 'low',
        potassiumReq: 'low',
        baseGdd: 40,
        minDaysToMaturity: 25,
        maxDaysToMaturity: 40,
    },
    {
        commonName: 'Rhubarb',
        latinName: 'Rheum x culturoum',
        family: 'Buckwheat',
        seedDepth: 3.0,
        minGermTemp: 40,
        maxGermTemp: 60,
        minGermTime: 0,
        sowOutdoorsBeforeFirstFrost: 3,
        minSoilPh: 5.5,
        maxSoilPh: 6.5,
        minGrowTemp: 40,
        maxGrowTemp: 6.5,
        seedSpacing: 24,
        sunExposure: 'part',
        waterFreq: 'med',
        nitrogenReq: 'low',
        phosphorusReq: 'low',
        potassiumReq: 'low'
    },
    {
        commonName: 'Rutabaga',
        latinName: 'Brassica napus',
        family: 'Cabbage',
        seedDepth: 0.5,
        minGermTemp: 60,
        maxGermTemp: 85,
        minGermTime: 3,
        maxGermTime: 5,
        sowOutdoorsBeforeLastFrost: 3,
        minSoilPh: 6.4,
        maxSoilPh: 7.2,
        minGrowTemp: 60,
        maxGrowTemp: 65,
        seedSpacing: 8,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'low',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        minDaysToMaturity: 60,
        maxDaysToMaturity: 90,
    },
    {
        commonName: 'Spinach',
        latinName: 'Spinacia oleracea',
        family: 'Beet',
        seedDepth: 0.5,
        minGermTemp: 50,
        maxGermTemp: 75,
        minGermTime: 7,
        maxGermTime: 14,
        sowIndoorsBeforeLastFrost: 5,
        transplantBeforeLastFrost: 2,
        sowOutdoorsBeforeFirstFrost: 8,
        sowOutdoorsBeforeLastFrost: 3,
        minSoilPh: 6.5,
        maxSoilPh: 7.5,
        minGrowTemp: 60,
        maxGrowTemp: 65,
        seedSpacing: 12,
        sunExposure: 'full',
        waterFreq: 'low',
        nitrogenReq: 'med',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        baseGdd: 40,
        minDaysToMaturity: 45,
        maxDaysToMaturity: 60,
    },
    {
        commonName: 'Squash (summer)',
        latinName: 'Cucurbita pepo',
        family: 'Cucumber',
        seedDepth: 1.0,
        minGermTemp: 70,
        maxGermTemp: 95,
        minGermTime: 6,
        maxGermTime: 10,
        sowIndoorsBeforeLastFrost: 4,
        transplantBeforeLastFrost: -1,
        sowOutdoorsBeforeFirstFrost: 10,
        minSoilPh: 6.0,
        maxSoilPh: 6.5,
        minGrowTemp: 65,
        maxGrowTemp: 75,
        seedSpacing: 18,
        sunExposure: 'full',
        waterFreq: 'high',
        nitrogenReq: 'high',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        minFlowerToHarvestTime: 4,
        maxFlowerToHarvestTime: 5,
        baseGdd: 50,
        minDaysToMaturity: 50,
        maxDaysToMaturity: 60,
    },
    {
        commonName: 'Squash (winter)',
        latinName: 'Cucurbita spp.',
        family: 'Cucumber',
        seedDepth: 1.0,
        minGermTemp: 70,
        maxGermTemp: 90,
        minGermTime: 6,
        maxGermTime: 10,
        sowIndoorsBeforeLastFrost: 4,
        transplantBeforeLastFrost: -1,
        sowOutdoorsBeforeFirstFrost: 16,
        minSoilPh: 5.5,
        maxSoilPh: 6.5,
        minGrowTemp: 65,
        maxGrowTemp: 75,
        seedSpacing: 18,
        sunExposure: 'part',
        waterFreq: 'high',
        nitrogenReq: 'high',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        minFlowerToHarvestTime: 40,
        maxFlowerToHarvestTime: 60,
        baseGdd: 50,
        minDaysToMaturity: 85,
        maxDaysToMaturity: 120,
    },
    {
        commonName: 'Strawberries',
        latinName: 'Fragaria spp.',
        family: 'Rose',
        seedDepth: 0,
        minGermTemp: 40,
        maxGermTemp: 60,
        minGermTime: 0,
        sowOutdoorsBeforeLastFrost: 3,
        minSoilPh: 6.0,
        maxSoilPh: 6.8,
        minGrowTemp: 60,
        maxGrowTemp: 80,
        seedSpacing: 12,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'med',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        baseGdd: 39,
    },
    {
        commonName: 'Sweet Potatoes',
        latinName: 'Ipomoea batatas',
        family: 'Morning glory',
        seedDepth: 0,
        minGermTemp: 0,
        minGermTime: 0,
        sowOutdoorsBeforeLastFrost: -2,
        sowOutdoorsBeforeFirstFrost: 25,
        minSoilPh: 5.5,
        maxSoilPh: 6.5,
        minGrowTemp: 65,
        maxGrowTemp: 90,
        seedSpacing: 18,
        sunExposure: 'full',
        waterFreq: 'low',
        nitrogenReq: 'low',
        phosphorusReq: 'low',
        potassiumReq: 'low',
        baseGdd: 60,
        gddToMaturity: 2600,
        minDaysToMaturity: 100,
        maxDaysToMaturity: 125,
    },
    {
        commonName: 'Swiss Chard',
        latinName: 'Beta vulgaris',
        family: 'Beet',
        seedDepth: 0.5,
        minGermTemp: 50,
        maxGermTemp: 85,
        minGermTime: 5,
        maxGermTime: 7,
        sowIndoorsBeforeLastFrost: 4,
        transplantBeforeLastFrost: 2,
        minSoilPh: 6.0,
        maxSoilPh: 7.0,
        minGrowTemp: 50,
        maxGrowTemp: 70,
        seedSpacing: 8,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'low',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        minDaysToMaturity: 50,
        maxDaysToMaturity: 60,
    },
    {
        commonName: 'Tomatillos',
        latinName: 'Physalis ixocarpa',
        family: 'Tomato',
        seedDepth: 0.25,
        minGermTemp: 70,
        maxGermTemp: 80,
        minGermTime: 7,
        maxGermTime: 14,
        sowIndoorsBeforeLastFrost: 4,
        transplantBeforeLastFrost: -2,
        minSoilPh: 6.0,
        maxSoilPh: 7.0,
        minGrowTemp: 60,
        maxGrowTemp: 80,
        seedSpacing: 3,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'low',
        phosphorusReq: 'low',
        potassiumReq: 'low',
        minDaysToMaturity: 75,
        maxDaysToMaturity: 100,
    },
    {
        commonName: 'Tomatoes',
        latinName: 'Lycoperscium esculentum',
        family: 'Tomato',
        seedDepth: 0.5,
        minGermTemp: 80,
        minGermTime: 6,
        maxGermTime: 8,
        sowIndoorsBeforeLastFrost: 6,
        transplantBeforeLastFrost: -2,
        sowOutdoorsBeforeFirstFrost: 19,
        minSoilPh: 5.8,
        maxSoilPh: 7.0,
        minGrowTemp: 70,
        seedSpacing: 15,
        sunExposure: 'full',
        waterFreq: 'high',
        nitrogenReq: 'med',
        phosphorusReq: 'high',
        potassiumReq: 'high',
        minFlowerToHarvestTime: 45,
        maxFlowerToHarvestTime: 50,
        baseGdd: 50,
        gddToMaturity: 1300,
        minDaysToMaturity: 70,
        maxDaysToMaturity: 90,
    },
    {
        commonName: 'Turnips',
        latinName: 'Brassica rapa',
        family: 'Cabbage',
        seedDepth: 0.5,
        minGermTemp: 50,
        maxGermTemp: 95,
        minGermTime: 2,
        maxGermTime: 5,
        sowOutdoorsBeforeLastFrost: 3,
        minSoilPh: 5.5,
        maxSoilPh: 6.8,
        minGrowTemp: 40,
        maxGrowTemp: 75,
        seedSpacing: 1,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'low',
        phosphorusReq: 'low',
        potassiumReq: 'low',
        minDaysToMaturity: 45,
        maxDaysToMaturity: 70,
    },
    {
        commonName: 'Watermelon',
        latinName: 'Citrullus lanatus',
        family: 'Cucumber',
        seedDepth: 0.5,
        minGermTemp: 80,
        maxGermTemp: 90,
        minGermTime: 3,
        maxGermTime: 10,
        sowIndoorsBeforeLastFrost: 3,
        transplantBeforeLastFrost: -2,
        sowOutdoorsBeforeFirstFrost: 16,
        minSoilPh: 6.0,
        maxSoilPh: 7.0,
        minGrowTemp: 70,
        maxGrowTemp: 85,
        seedSpacing: 18,
        sunExposure: 'full',
        waterFreq: 'med',
        nitrogenReq: 'high',
        phosphorusReq: 'med',
        potassiumReq: 'med',
        minFlowerToHarvestTime: 45,
        maxFlowerToHarvestTime: 60,
        baseGdd: 55,
        minDaysToMaturity: 80,
        maxDaysToMaturity: 100,
    }
];

db
    .sync({ force: true })
    .then(() => {
        console.log('old data dropped, now inserting crops');
        return Promise.each(crops, crop => Crop.create(crop));
    })
    .then(() => {
        console.log('crops created, closing db');
    })
    .catch(err => console.error('problem', err))
    .finally(() => db.close());
